# Generated by Django 5.2.7 on 2025-10-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(editable=False, max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '6. Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(help_text='E.g., Bronze, Standard, Enterprise.', max_length=100)),
                ('duration_unit', models.CharField(choices=[('ONETIME', 'One-Time'), ('MONTH', 'Month(s)'), ('QUARTER', 'Quarterly'), ('HALFYR', 'Half-Yearly'), ('YEAR', 'Yearly'), ('PROJECT', 'Project')], help_text='The frequency of the service.', max_length=10)),
                ('duration_value', models.CharField(help_text="E.g., 'Project', '1 Month', '12 Months'.", max_length=50)),
                ('min_price_usd', models.DecimalField(decimal_places=2, help_text='Minimum price.', max_digits=10)),
                ('max_price_usd', models.DecimalField(decimal_places=2, help_text='Maximum price (Set same as min if fixed price).', max_digits=10)),
                ('button_type', models.CharField(choices=[('PRICE', 'Display Price Button'), ('CART', 'Add to Cart Button'), ('CONTACT', 'Contact to Sale Button')], default='CART', help_text='Controls the button text/action on the frontend.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this package will not appear on the website.')),
            ],
            options={
                'verbose_name_plural': '3. Packages (Under Services)',
                'ordering': ['min_price_usd'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Internal code (e.g., DBT, PAYPAL, STRIPE).', unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='If true, users can select this option at checkout.')),
                ('is_visible', models.BooleanField(default=True, help_text='If true, the method is shown on the payment page (even if disabled).')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '5. Payment Methods',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('short_description', models.CharField(help_text='A short teaser for the class detail page.', max_length=255)),
                ('detailed_description', models.TextField(blank=True, help_text='Full details for the service page.')),
            ],
            options={
                'verbose_name_plural': '2. Services (Under Classes)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief summary for the index page.')),
                ('order', models.IntegerField(default=0, help_text='Display order on the index page.')),
            ],
            options={
                'verbose_name_plural': '1. Service Classes (Categories)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mpgepmcservs.package')),
            ],
            options={
                'verbose_name_plural': '4. Package Features',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='mpgepmcservs.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mpgepmcservs.serviceclass'),
        ),
    ]
